import { ArrowLeft, Cookie, FileText, LockKeyhole, ShieldCheck } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import Logo from '../components/Logo'

const DATA={
  privacy:{title:'Privacy Policy',Icon:LockKeyhole,intro:'What CodaVybes stores, why we store it, and what stays private.',sections:[['Account & profile','We store account identity, profile fields, age-safety information, preferences and the social data needed to run CodaVybes. Your exact date of birth is treated as restricted account data and is not exposed as a public profile field.'],['Public vs private','Public posts, Aura counts, profile fields you choose to expose and public Rooms may be visible to eligible users. Direct and group chat messages are restricted to conversation participants and authorized safety workflows.'],['Safety & moderation','Reports, blocks, account sanctions and anti-abuse signals may be retained to protect users, enforce rules and investigate abuse.'],['Your choices','Settings control discovery, notifications and appearance. Account deletion and data export should be handled through account-management flows as the product matures.']]},
  cookies:{title:'Cookie & Storage Policy',Icon:Cookie,intro:'A simple view of browser storage and optional analytics.',sections:[['Essential storage','CodaVybes uses authentication/session storage, consent state, theme preference and security-related storage required for the app to function.'],['Optional analytics','Analytics should only be enabled when consented to. Advertising or sponsorship measurement should not expose private chat content.'],['Changing your choice','Use Settings → Review privacy choices to reset your consent choice, or clear site data in your browser.']]},
  security:{title:'Security',Icon:ShieldCheck,intro:'How the product is designed to defend accounts, chats, Aura and admin actions.',sections:[['Server authority','Aura awards, ranks, game results, verification, admin actions and commerce settlements are server/database controlled. The browser is never trusted as the authority.'],['Access control','Supabase Auth, RLS, member checks, age-safety pools, block rules and role-based admin controls protect data access.'],['Secrets','Service-role and privileged credentials must stay server-side and never be shipped in the browser bundle.'],['Reporting','Use in-app reporting for harassment, threats, impersonation, unsafe content or suspicious accounts.']]},
  terms:{title:'Terms of Use',Icon:FileText,intro:'The basic rules for using CodaVybes responsibly.',sections:[['Age','CodaVybes is currently available to users age 10+. Age-safety pools and local legal requirements may impose stricter rules.'],['Conduct','Do not harass, threaten, impersonate, exploit, scam or attempt to bypass safety systems.'],['Aura & rankings','Aura is earned reputation. Manipulation, farming, fake accounts or automated abuse may result in ignored Aura, restrictions or account action.'],['Sponsored content','Paid placements are labeled Sponsored. A sponsorship does not change organic Aura or verification status.']]},
}
export default function LegalPage({type:fixedType}){const params=useParams();const navigate=useNavigate();const key=fixedType||params.type||'privacy';const page=DATA[key]||DATA.privacy;const Icon=page.Icon;return <div className="legal-page"><header><button className="icon-btn" onClick={()=>navigate(-1)}><ArrowLeft size={19}/></button><Logo/></header><main className="legal-card surface"><div className="legal-hero"><span><Icon size={24}/></span><p className="eyebrow">CODAVYBES · CODABITE</p><h1>{page.title}</h1><p>{page.intro}</p></div>{page.sections.map(([h,b])=><section key={h}><h2>{h}</h2><p>{b}</p></section>)}<footer><Link to="/privacy">Privacy</Link><Link to="/cookies">Cookies</Link><Link to="/security">Security</Link><Link to="/terms">Terms</Link></footer></main></div>}
