import { useEffect, useMemo, useState } from 'react'
import { Activity, AlertTriangle, Gamepad2, Globe2, MapPin, MessageCircle, PackageCheck, Radio, ShieldCheck, Smartphone, Users, Wifi } from 'lucide-react'

function fmt(n){return Number(n||0).toLocaleString()}
function when(v){return v?new Date(v).toLocaleString():'—'}
function money(cents,currency){try{return new Intl.NumberFormat(undefined,{style:'currency',currency:currency||'USD'}).format(Number(cents||0)/100)}catch{return `${Number(cents||0)/100} ${currency||''}`}}
function initials(name='CV'){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'CV'}
function activityDetail(value){if(value==null)return 'Activity recorded';if(typeof value==='string')return value;try{return Object.entries(value).slice(0,4).map(([k,v])=>`${k.replaceAll('_',' ')}: ${typeof v==='object'?JSON.stringify(v):String(v)}`).join(' · ')||'Activity recorded'}catch{return 'Activity recorded'}}

function LiveStat({icon:Icon,label,value,note}){return <article className="hq-stat hq-live-stat"><div className="hq-stat__icon"><Icon size={18}/></div><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</article>}

function MiniList({rows=[],empty='No data yet',render}){return <div className="hq-analytics-mini-list">{rows.length?rows.map((row,i)=><div key={i}>{render(row)}</div>):<p>{empty}</p>}</div>}

export default function AnalyticsPanel({overview,liveUsers,errors,activity=[],releases,windowHours,onWindow,onOpenUser,onSaveRelease,canEdit,superAdmin,busy}){
  const [release,setRelease]=useState({platform:'android',version:'13.4.0',build_number:13400,download_url:'',release_notes:'',required:false,active:true})
  const [saving,setSaving]=useState(false)
  useEffect(()=>{if(!release.version)setRelease(v=>({...v,version:'13.4.0'}))},[])
  const platformRows=overview?.platforms||[]
  const revenue=overview?.revenue_by_currency||[]
  const periodLabel=windowHours===1?'1 hour':windowHours===24?'24 hours':windowHours===168?'7 days':windowHours===720?'30 days':`${windowHours}h`
  const activeLocations=useMemo(()=>liveUsers.filter(x=>x.city||x.country).length,[liveUsers])
  const save=async()=>{if(!canEdit||saving)return;setSaving(true);try{await onSaveRelease(release);setRelease(v=>({...v,id:null,download_url:'',release_notes:'',required:false}))}finally{setSaving(false)}}
  const edit=(row)=>setRelease({id:row.id,platform:row.platform,version:row.version,build_number:row.build_number,download_url:row.download_url||'',release_notes:row.release_notes||'',required:!!row.required,active:row.active!==false})
  return <div className="hq-view hq-analytics-view">
    <div className="hq-analytics-head"><div><span className="hq-live-label"><i/> LIVE COMMAND CENTER</span><h2>Real product analytics</h2><p>Fresh operational presence updates every ~5 seconds. Historical telemetry starts with V13.4; product counts come from the real database, not mock data.</p></div><div className="hq-window-picker">{[[1,'1H'],[24,'24H'],[168,'7D'],[720,'30D']].map(([h,l])=><button key={h} className={windowHours===h?'is-active':''} onClick={()=>onWindow(h)}>{l}</button>)}</div></div>

    <div className="hq-kpis hq-analytics-kpis">
      <LiveStat icon={Radio} label="Active now" value={fmt(overview?.active_users)} note={`${fmt(overview?.active_sessions)} sessions`}/>
      <LiveStat icon={Users} label={`Unique / ${periodLabel}`} value={fmt(overview?.unique_users_period)} note={`+${fmt(overview?.new_users_period)} signups`}/>
      <LiveStat icon={MessageCircle} label="Messages" value={fmt(overview?.messages_period)} note={`${fmt(overview?.posts_period)} posts`}/>
      <LiveStat icon={Activity} label="Engagement" value={fmt((overview?.comments_period||0)+(overview?.reactions_period||0)+(overview?.shares_period||0))} note={`${fmt(overview?.events_period)} consented events`}/>
      <LiveStat icon={Gamepad2} label="Games" value={fmt(overview?.games_period)} note={`${fmt(overview?.rooms_period)} rooms`}/>
      <LiveStat icon={AlertTriangle} label="Client errors" value={fmt(overview?.errors_period)} note={`${fmt(overview?.plus_active)} CodaVybes+ active`}/>
    </div>

    <section className="hq-analytics-platforms">{['web','android','windows'].map(platform=>{const row=platformRows.find(x=>x.platform===platform)||{};return <article className="hq-card hq-platform-stat" key={platform}><div><span className={`hq-platform-mark is-${platform}`}>{platform==='android'?<Smartphone size={18}/>:<Globe2 size={18}/>}</span><div><small>{platform.toUpperCase()}</small><h3>{fmt(row.active_users)} active now</h3></div></div><dl><div><dt>Users / {periodLabel}</dt><dd>{fmt(row.users_period)}</dd></div><div><dt>Sessions</dt><dd>{fmt(row.sessions_period)}</dd></div><div><dt>Installs seen</dt><dd>{fmt(row.installs_seen)}</dd></div></dl></article>})}</section>

    <div className="hq-grid-2 hq-analytics-grid">
      <article className="hq-card"><div className="hq-card-title"><div><span>PLATFORM HEALTH</span><h3>Versions in use</h3></div><PackageCheck size={18}/></div><MiniList rows={overview?.versions||[]} render={x=><><span><strong>{x.platform} · v{x.app_version}</strong><small>Last seen {when(x.last_seen)}</small></span><b>{fmt(x.users)} users</b></>}/></article>
      <article className="hq-card"><div className="hq-card-title"><div><span>GEOGRAPHY</span><h3>Coarse location signals</h3></div><MapPin size={18}/></div><MiniList rows={overview?.countries||[]} empty="No edge geography available yet" render={x=><><span><strong>{x.country||'Unknown'}</strong><small>Derived only when the hosting edge supplies a country header.</small></span><b>{fmt(x.users)}</b></>}/></article>
      <article className="hq-card"><div className="hq-card-title"><div><span>PRODUCT</span><h3>Top routes</h3></div><Activity size={18}/></div><MiniList rows={overview?.top_routes||[]} render={x=><><span><strong>{x.route}</strong><small>{fmt(x.sessions)} sessions</small></span><b>{fmt(x.users)} users</b></>}/></article>
      <article className="hq-card"><div className="hq-card-title"><div><span>CONSENTED ANALYTICS</span><h3>Top events</h3></div><Activity size={18}/></div><MiniList rows={overview?.top_events||[]} empty="No optional analytics events yet" render={x=><><span><strong>{x.event_name.replaceAll('_',' ')}</strong><small>{fmt(x.users)} users</small></span><b>{fmt(x.count)}</b></>}/></article>
    </div>

    <div className="hq-analytics-money"><span><ShieldCheck size={16}/> Paid orders / {periodLabel}: <b>{fmt(overview?.paid_orders_period)}</b></span>{revenue.map(r=><span key={r.currency}><b>{money(r.amount_cents,r.currency)}</b> · {fmt(r.orders)} orders</span>)}</div>

    <div className="hq-analytics-section-head"><div><span><i/> LIVE USERS</span><h3>{fmt(liveUsers.length)} identities online</h3></div><small>{activeLocations} with coarse geo · sensitive network fields limited by role</small></div>
    <div className="hq-table-wrap hq-live-table"><table className="hq-table"><thead><tr><th>User</th><th>Platform</th><th>Route</th><th>Device</th><th>Network</th><th>Location</th>{superAdmin&&<th>IP / precise</th>}<th>Last heartbeat</th></tr></thead><tbody>{liveUsers.length?liveUsers.map(u=><tr key={u.user_id} className="hq-live-user-row" onClick={()=>onOpenUser(u.user_id)}><td><div className="hq-table-user"><div>{initials(u.display_name||u.username)}</div><span><strong>{u.display_name||u.username}</strong><small>@{u.username}</small></span></div></td><td><b className={`hq-platform-pill is-${u.platform}`}>{u.platform}</b><small>v{u.app_version}</small></td><td><code>{u.route}</code><small>{u.presence_status}</small></td><td>{u.device_type||'—'}<small>{[u.os_name,u.browser_name].filter(Boolean).join(' · ')||'—'}</small></td><td>{u.network||'—'}<small>{u.timezone||'—'}</small></td><td>{[u.city,u.region,u.country].filter(Boolean).join(', ')||'—'}<small>{u.location_consent?'precise opt-in':'no precise opt-in'}</small></td>{superAdmin&&<td>{u.ip_address||'—'}<small>{u.latitude!=null&&u.longitude!=null?`${Number(u.latitude).toFixed(5)}, ${Number(u.longitude).toFixed(5)} ±${Math.round(u.location_accuracy_m||0)}m`:'—'}</small></td>}<td>{when(u.last_seen)}</td></tr>):<tr><td colSpan={superAdmin?8:7}><div className="hq-empty"><Radio size={24}/><h3>No active telemetry yet</h3><p>Open a V13.4 client while signed in. Presence will appear after its first heartbeat.</p></div></td></tr>}</tbody></table></div>

    <div className="hq-analytics-section-head"><div><span><i/> LIVE ACTIVITY</span><h3>Real database activity</h3></div><small>Posts, comments, reactions, shares, messages (metadata only), games, Aura and wallet events.</small></div>
    <div className="hq-card hq-activity-card"><div className="hq-activity-stream">{activity.length?activity.slice(0,80).map((item,i)=><button key={`${item.created_at}-${item.user_id||'system'}-${i}`} onClick={()=>item.user_id&&onOpenUser(item.user_id)} disabled={!item.user_id}><span className="hq-activity-icon"><Activity size={15}/></span><span className="hq-activity-main"><strong>{String(item.activity_type||'activity').replaceAll('_',' ')}</strong><small>{item.username?`@${item.username}`:'system'}{item.platform?` · ${item.platform}`:''}{item.entity_type?` · ${item.entity_type}`:''}</small><em>{activityDetail(item.detail)}</em></span><time>{when(item.created_at)}</time></button>):<div className="hq-empty"><Activity size={24}/><h3>No activity yet</h3><p>This stream reads real CodaVybes database activity. It does not generate sample rows.</p></div>}</div></div>

    <div className="hq-grid-2 hq-analytics-bottom">
      <article className="hq-card"><div className="hq-card-title"><div><span>ERROR STREAM</span><h3>Recent client errors</h3></div><AlertTriangle size={18}/></div><div className="hq-error-stream">{errors.length?errors.slice(0,30).map(e=><button key={e.id} onClick={()=>onOpenUser(e.user_id)}><span><strong>{e.error_kind}</strong><small>@{e.username||'user'} · {e.platform} v{e.app_version} · {e.route}</small></span><p>{e.message||'No message'}</p><time>{when(e.created_at)}</time></button>):<div className="hq-empty"><ShieldCheck size={24}/><h3>No recorded client errors</h3><p>Error capture requires optional analytics consent.</p></div>}</div></article>
      <article className="hq-card"><div className="hq-card-title"><div><span>RELEASE CONTROL</span><h3>Web · Android · Windows updates</h3></div><PackageCheck size={18}/></div><div className="hq-release-form"><div className="hq-field-grid"><label><span>Platform</span><select value={release.platform} onChange={e=>setRelease(v=>({...v,platform:e.target.value}))}><option value="web">Web</option><option value="android">Android</option><option value="windows">Windows</option></select></label><label><span>Version</span><input value={release.version} onChange={e=>setRelease(v=>({...v,version:e.target.value}))} placeholder="13.4.0"/></label><label><span>Build number</span><input type="number" min="1" value={release.build_number} onChange={e=>setRelease(v=>({...v,build_number:e.target.value}))}/></label></div><input placeholder="Download / store URL (optional for web)" value={release.download_url} onChange={e=>setRelease(v=>({...v,download_url:e.target.value}))}/><textarea placeholder="Release notes shown in the app" value={release.release_notes} onChange={e=>setRelease(v=>({...v,release_notes:e.target.value}))}/><div className="hq-release-checks"><label><input type="checkbox" checked={release.required} onChange={e=>setRelease(v=>({...v,required:e.target.checked}))}/> Required update</label><label><input type="checkbox" checked={release.active} onChange={e=>setRelease(v=>({...v,active:e.target.checked}))}/> Active</label></div><div className="hq-form-actions"><button className="hq-btn hq-btn--gold" disabled={!canEdit||saving||busy||!release.version} onClick={save}>{saving?'Saving…':'Save release'}</button>{release.id&&<button className="hq-btn" onClick={()=>setRelease({platform:'android',version:'13.4.0',build_number:13400,download_url:'',release_notes:'',required:false,active:true})}>New release</button>}</div></div><div className="hq-release-list">{releases.slice(0,10).map(r=><button key={r.id} onClick={()=>edit(r)}><span><strong>{r.platform} · v{r.version}</strong><small>build {r.build_number} · {r.required?'required':'optional'} · {r.active?'live':'off'}</small></span><time>{new Date(r.published_at).toLocaleDateString()}</time></button>)}</div></article>
    </div>

    <div className="hq-privacy-note"><ShieldCheck size={18}/><div><strong>Privacy-aware by design</strong><p>Private message bodies, passwords, auth tokens and secrets are never analytics fields. IP metadata is short-lived. Latitude/longitude appears only after a separate user opt-in and only to Super Admin. Network/location availability depends on device and edge headers, so blank means “not supplied”, never guessed.</p></div></div>
  </div>
}
